---
- name: test ansible vault
  hosts: all
  become: true
  vars_files:
  - ./pass.yml
  tasks:
  - name: clone repo
    git:
      repo: https://{{ user }}:{{ password }}@github.com/Glowczyns/sejf.git
      dest: /etc/ansible/sejf
   
