---
- hosts: all
  name: uninstall packages
  become: true 
  tasks:
  - name: stop apache service
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"
  - name: uninstall apache
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"

  - name: stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"
  - name: uninstall httpd
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

