---
# tasks file for setup-apache
  - name: install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: install_apache
    notify: start httpd service
    
  - name: install apache
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install_apache
    notify: start apache service

  - name: copy index.html
    copy:
      src: ./index.html
      dest: /var/www/html
      mode: 0777

  - name: modify a port
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port2 }}
    when: ansible_os_family == "RedHat"
    notify: restart httpd

  - name: modify a port
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: '^# /etc/apache2/sites-enabled/000-default.conf'
      line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart apache

